import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';import { Sidebar } from '@/components/Sidebar';
;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased grid",
          inter.className
        )}
      >
        <Sidebar />
        <main className="[grid-area:content] sm:px-4 overflow-y-auto h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
